language: python

branches:
  except:
  - dev

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - g++-6
        - cmake
        - gfortran
        - liblapack-dev
        - libfftw3-dev
        - libsndfile1-dev
    env:
    - CXX=g++-6
    - CC=gcc-6
    - PIP=pip
    python: 3.6.5

install:
- "$PIP install -r requirements.txt --upgrade"
- python --version
- cmake -H. -Bbuild-proj
- echo "Building tests"
- cd build-proj
- cmake --build . --target all
- cd ..

script:
- pip install .
- echo "Performing python library tests"
- python ./test/test_libtempo_py/integration_test.py
- echo "Performing CPP tests"
- cd build-proj
- "./test/test_libtempo/test_libtempo"
- "./test/test_main/test_main"
- cd ..

notifications:
  email: false

deploy:
  provider: pypi
  user: egordm
  password:
    secure: ZPQnF+//2rtwo/PpcatEQNG4u/FezKO+29liwCAhsBsFrgC+NGmVxBJuAo7LMIuqoFIh2FDUqSYzE4zPgnPsJ9MfYvRSmy7fIwBOvdQEIHVuSm1irr3kC/G4nOsngyKQiKCJsXkhTx5O9Ktd7P66T/klPS0g1G5dHzUr4e/TOyeRSJwrTyHt8puuX4QhzL8Jk2O/4A8hZb3x3Z+YvU9eNVZyqla62cGKgoc6FCY+QtqYiOA8cYAJ+jW+4SNiWbYiXy+H784/8RJK5nvBHCsFlgSSdCy0vp9RrhkNcMnr/sj/1nHbs9luD5l+oqMiqEYf0D3+Ipm7TjDPshf1YBcTgYiiasFSiemLBUgMr9VLuPbnMAmtQkxCvM1XyuK2JBwFZ/EwRLoUB61uPpnNXwOb7XCrbr8el+lbkLIYLM5Fu5B28k2H32XLzInVvIafTpfA8MkbF/2q66cYu0K0IMEWGYrP6KTHS5g5TCLgGXJufCtbg/DuZ0vaCTNElSTHE/d5AR/+NCQCHLeOsrIvgamWe5+6qIdSGV3m9UX54wkFziaRc0xAkYSpTUgO0ZuuPiebegf/rUiVSV58TNOK/d39ulV0FForZr+z0j8jCKc4FHeGpBnMN/m4XWYu6wI7TEMU7E+PBnktQCyRIyYVmKEScvTgcDo7qrOF28r+O9FQ0uM=
  distributions: sdist bdist_wheel
#  on:
#    tags: true