language: python

branches:
  except:
  - dev

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages:
          - gcc-6
          - g++-6
          - cmake
          - gfortran
          - liblapack-dev
          - libfftw3-dev
          - libsndfile1-dev
    env:
    - CXX=g++-6
    - CC=gcc-6
    - PIP=pip
    python: 3.6.5

install:
  - $PIP install -r requirements.txt --upgrade
  - python --version

script:
  - pip install .

notifications:
  email: false
