language: python

branches:
  except:
  - dev

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - g++-6
        - cmake
        - gfortran
        - liblapack-dev
        - libfftw3-dev
        - libsndfile1-dev
    env:
    - CXX=g++-6
    - CC=gcc-6
    - PIP=pip
    python: 3.6.5

install:
- "$PIP install -r requirements.txt --upgrade"
- python --version
- cmake -H. -Bbuild-proj
- echo "Building tests"
- cd build-proj
- cmake --build . --target all
- cd ..

script:
- pip install .
- echo "Performing python library tests"
- python ./test/test_libtempo_py/integration_test.py
- echo "Performing CPP tests"
- cd build-proj
- "./test/test_libtempo/test_libtempo"
- "./test/test_main/test_main"
- cd ..

notifications:
  email: false

deploy:
  provider: pypi
  user: egordm
  password:
    secure: QGleaUuw3ZMw6SA1IUG6VJzFsk21UMHtPrWABx654hZuEECaul2X1StBZ7kMjAPk25CVKNRWu98KyWRiG+C7bKm1f5hSUKcwehE40QHecMUDC6tkWYPJcFkQs9fPe5UOSV/DFRAMjqjxveuBv7YBLFnL9LJWrQXbidhCEqTDXdvwds4r2hr4rJf9Xt7WlzuKjlyZD2Bwq+PDC0gIZewEoUlHI8+UAv1eU+4Zt4Humg0fOaD79ipaPVWXoS1jzR7WLjABASTQU38kySELlWvBCZ3dRo74txkoof4C96CJKdjkDNe/vSEAGjD26JGQw2UI3EyOlUW0uqlgcQp6KelCu4BxbD7uVWq/dgFqcJ18z+YdC8TKN7bQjSgfzmpqUVTGG5nyMv+BPj93BI+6M3pdJE2y4Yv177DFd8BHVSJzPsHfXCRBtVTf09C9sIb3dJLyV185QHGFSzaCkdhhzSJ+HXNW+5AcWrFXPON0IMO4U7ngrMWzPdLYEoifLKx+WTPj41OlxBNlfXYrkznwAjDSkMOmbfWTF4t3vShCeAE5GhaL+QB5xEnkKDum7C//+XeZBOK4KzcScwsIALWkTdZTD2SKQz05wqq99FNvdgEt6pOIsgF1rn+ebxy3TlBxOGRF6St8dHaPj9QxswFE3usW9B/MEajIcagd/Sg7Vo1ow64=
  distributions: sdist bdist_wheel
  on:
    tags: true
