language: python

branches:
  except:
  - dev

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: PIP=pip
  - os: osx
    language: generic
    env: PIP=pip2

env:
  global:
  - CIBW_BEFORE_BUILD="yum install -y wget gcc gcc-c++ libgfortran lapack fftw libsndfile-devel && wget https://cmake.org/files/v3.12/cmake-3.12.3.tar.gz && tar zxvf cmake-3.* && cd cmake-3.* && ./bootstrap --prefix=/usr/local && make -j$(nproc) && make install && cd .. && cmake --version && pip install -r requirements.txt"

script:
- $PIP install -r requirements.txt
- $PIP install cibuildwheel==0.10.0
- cibuildwheel --output-dir wheelhouse

notifications:
  email: false