language: python

branches:
  except:
  - dev

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: PIP=pip
  - os: osx
    language: generic
    env: PIP=pip2

env:
  global:
  - CIBW_BEFORE_BUILD="yum install -y make gcc gcc-c++ libgfortran lapack fftw libsndfile-devel && curl -LO http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/c/cmake3-3.12.1-1.el7.x86_64.rpm && yum localinstall cmake3-3.12.1-1.el7.x86_64.rpm && cmake --version && pip install -r requirements.txt"

script:
- $PIP install -r requirements.txt
- $PIP install cibuildwheel==0.10.0
- cibuildwheel --output-dir wheelhouse

notifications:
  email: false