language: python

branches:
  except:
  - dev

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: PIP=pip
  - os: osx
    language: generic
    env: PIP=pip2

env:
  global:
  - CIBW_BEFORE_BUILD="yum install -y gcc gcc-c++ cmake libgfortran lapack fftw libsndfile-devel && pip install ."

script:
- $PIP install -r requirements.txt
- $PIP install cibuildwheel==0.10.0
- cibuildwheel --output-dir wheelhouse

notifications:
  email: false