language: python

branches:
  except:
  - dev

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: PIP=pip
  - os: osx
    language: generic
    env: PIP=pip2

env:
  global:
  - CIBW_BEFORE_BUILD="yum install -y gcc-6 g++-6 cmake gfortran liblapack-dev libfftw3-dev libsndfile1-dev && export CXX=g++-6 && export CC=gcc-6 && pip install ."

script:
- $PIP install -r requirements.txt --upgrade
- $PIP install cibuildwheel==0.10.0
- cibuildwheel --output-dir wheelhouse

notifications:
  email: false